# Numpy Array

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_mat_arr  = np.array(my_mat)

In [11]:
my_mat_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.zeros((3,7))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [20]:
np.ones((2,7))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [21]:
np.linspace(0,10,5) # 5 evenly space points

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [22]:
np.linspace(0,10,20) # 20 evenly space points

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [23]:
np.linspace(0,10,50) # 50 evenly space points  ... one dimensional array.

# This is different then arange.

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [24]:
np.eye(4)  # 4x4 matrix ,... with diagonal is 1 and rest of numbers are 0s.

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [25]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [28]:
np.random.rand(5) # 1D array of 5 numbers

array([ 0.00616518,  0.98368383,  0.1117511 ,  0.90169231,  0.41266385])

In [29]:
np.random.rand(2,5)  # 2D array of random numbers

array([[ 0.37581294,  0.9451474 ,  0.27203952,  0.75674269,  0.56567803],
       [ 0.01509602,  0.55499111,  0.89976299,  0.90950913,  0.26338462]])

In [32]:
np.random.rand(4,5)  #2D array

array([[ 0.24096697,  0.16935977,  0.88146871,  0.12869404,  0.15183344],
       [ 0.79624344,  0.22581331,  0.59818357,  0.29017652,  0.41083705],
       [ 0.64520897,  0.28428678,  0.72877011,  0.42077907,  0.90141279],
       [ 0.82993127,  0.82819448,  0.30308956,  0.98039114,  0.66806448]])

In [33]:
np.random.randn(4)  # numbers arpund 0s. Means positive or negative

array([-1.52991708,  0.24486022,  0.58743976,  0.0779746 ])

In [34]:
np.random.randn(5)

array([-0.75065806,  0.46893185, -2.16176088, -1.03147697, -0.14350358])

In [35]:
np.random.randn(3,7)   #2D array

array([[ 0.71278361, -1.31060822, -0.96867674, -0.26842286,  0.49139968,
        -0.0133439 , -1.54758745],
       [ 0.27375191,  0.35532758, -1.40719261,  0.35627371, -1.36776872,
         0.83370655, -2.0899906 ],
       [-1.78473039, -0.97207721, -0.10021832,  1.9261337 ,  2.07691985,
        -1.01217547,  0.63356168]])

In [38]:
np.random.randint(1,100)  # 1 number will be return

92

In [39]:
np.random.randint(1,100,10)  # 10 number will be return -- 1 D array

array([87, 51, 55, 95, 26, 58, 19, 87, 58, 86])

In [44]:
np.random.randint(1,100 ,(4,5)) # 2D array of int

array([[72,  7, 68, 25, 97],
       [95, 64,  7, 39, 98],
       [64, 76, 56, 66, 31],
       [96, 77, 83, 58, 56]])

In [45]:
arr = np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr = np.random.randint(0,50,10)

In [48]:
ranarr

array([22, 37, 13,  8, 43, 46, 46, 41, 42, 26])

In [51]:
arr.reshape(5,5)   # reshaping array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr.max()

46

In [53]:
ranarr.min()

8

In [54]:
ranarr

array([22, 37, 13,  8, 43, 46, 46, 41, 42, 26])

In [56]:
ranarr.argmax() # it will be return index location of 49.

5

In [57]:
ranarr.argmin()

3

In [59]:
arr.shape

(25,)

In [60]:
arr.reshape(5,5)  # reshaping

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr = arr.reshape(5,5)

In [62]:
arr.shape

(5, 5)

In [63]:
arr.dtype

dtype('int32')

# Numpy Indexing and Selection

In [64]:
arr =np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[4]

4

In [67]:
arr[1:5]

array([1, 2, 3, 4])

In [68]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [69]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[:5]

array([0, 1, 2, 3, 4])

In [71]:
arr[:5] = 50

In [72]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [74]:
arr = np.arange(0,11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
slice_of_arr = arr[:6] # getting subset of orginial array

In [79]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [81]:
# now let's change slice of array

slice_of_arr[:]= 99

In [82]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
# now check original array from which slice of array was derived
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
# this meand changing anything in slice of array will be change original arrary as well

In [85]:
# creating copy of array

arr_copy = arr.copy()

In [86]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr_copy[:] = 100

In [89]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
# now check original array.. it will not have changed array

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [92]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [93]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [94]:
arr_2d[1]

array([20, 25, 30])

In [95]:
arr_2d[0]

array([ 5, 10, 15])

In [97]:
arr_2d[0][1] #1st row and 2nd column

10

In [98]:
arr_2d[1][1]

25

In [100]:
arr_2d[2][2]

45

In [102]:
arr_2d[2,2]  # passing row and column as a list

45

In [104]:
arr_2d[:2,1:]  # getting matrices of original. Passing :2 as row selection and 1: for column selection

array([[10, 15],
       [25, 30]])

In [106]:
arr_2d[1:,1:] # Getting bottom right corner

array([[25, 30],
       [40, 45]])

In [108]:
arr_2d[1:,:2] # Getting left bottom corner

array([[20, 25],
       [35, 40]])

In [109]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [111]:
arr_2d[:,1:] # All rows and 2nd & 3rd Columns

array([[10, 15],
       [25, 30],
       [40, 45]])

In [112]:
arr = np.arange(1,11)

In [113]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr > 5  # boolean array

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [116]:
arr < 7

array([ True,  True,  True,  True,  True,  True, False, False, False, False], dtype=bool)

In [117]:
bool_arr = arr > 6

In [118]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [119]:
arr[bool_arr]

array([ 7,  8,  9, 10])

In [120]:
arr[arr>8]

array([ 9, 10])

In [121]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [122]:
arr[arr<3]

array([1, 2])

In [123]:
arr_2d = np.arange(0,50).reshape(5,10)  # for practice

In [124]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [125]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operation

In [128]:
arr = np.arange(0,11)

In [129]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [131]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [133]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [134]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [135]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [136]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [137]:
1/0  # python will give you erro

ZeroDivisionError: division by zero

In [139]:
arr /arr  # here first element is 0. so 0/0 will not issue error. It will just issue message and proceed further

C:\Python3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [140]:
1/arr

C:\Python3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [141]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Universal array function

In [142]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [143]:
np.exp(arr)  # expontial of each element

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [145]:
arr.max()

10

In [146]:
np.sin(arr)  # it will give sin value of each element

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [148]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
np.log(arr) # log of 0 is giving as inf. giving warning message and proceeding further.

C:\Python3\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

# Exercise

## Create array of 10 zeros

In [150]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [151]:
## Create array of 10 ones

In [153]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Create array of 10 five

In [176]:
# Create array of 10 fives
arr = np.ones(10)
arr[:] = 5
arr

#or 
np.ones(10)*5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [156]:
#array of integer from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [177]:
#array of even element integer from 10 to 50 
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [178]:
# Create 3X3 matrices ranging from 0 to 8 
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
# 3X3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [179]:
#Generate random number between 0 to 1 
np.random.rand(1)

array([ 0.58915599])

In [182]:
# 25 random number with standard distribution
np.random.randn(25)

array([-0.53391929, -0.38504501, -0.58310486, -0.2317321 , -0.37116498,
       -0.45212947,  2.06086864,  0.1058648 , -1.23365174, -0.47382334,
       -0.36653085, -1.67722467,  0.10021513,  1.06693332, -0.08896875,
        0.82168789,  1.24554638, -0.72806404,  1.03450995, -0.88325933,
        0.71424245, -0.05982354,  1.75410632,  1.48880154,  0.57982703])

In [186]:
np.linspace(0,1,100).reshape(10,10)

# OR

np.arange(1,101).reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [187]:
# Array of 20 lineraly spaced points between 0 to 1

np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [189]:
#Sample metrix for next few examples

mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [190]:
# grab 12 to 25 array

mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [191]:
#just get number 20

mat[3,4]

20

In [192]:
# displaying mat again for ref
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [195]:
# Get 2,7,12  column

mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [198]:
# Get [21, 22, 23, 24, 25]

mat[-1]
# or 
mat[-1:]

array([[21, 22, 23, 24, 25]])

In [200]:
# Get this 
# [16, 17, 18, 19, 20],
# [21, 22, 23, 24, 25]

mat[-2:]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [201]:
# displaying mat again for ref
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [205]:
# Get the sum of all elements in array.

mat.sum()

# or 

np.sum(mat)

325

In [207]:
mat.std()
# or

np.std(mat)


7.2111025509279782

In [214]:
# Get the sum of all columns in mat

mat.sum(axis = 0)

array([55, 60, 65, 70, 75])